<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.2">
  <POU Name="Payload" Id="{01decef4-4932-45b1-b8fd-b868843e0df2}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Payload EXTENDS Serializable
VAR_INPUT
	timer : TON;
	k : INT;
	j : INT;
END_VAR

VAR
		
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[timer();
]]></ST>
    </Implementation>
    <LineIds Name="Payload">
      <LineId Id="20" Count="0" />
      <LineId Id="33" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>