<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.2">
  <POU Name="Test" Id="{7dccdeb8-e15e-42f2-a785-a226f40a2e5e}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Test
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	i,j,k : INT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Test">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>